format_version: 10
pipelines:
    CppOverrideArtifacts:
        group: CppOverride
        label_template: ${COUNT}
        lock_behavior: none
        display_order: -1
        materials:
            CppOverrideMainTrigger:
                ignore_for_scheduling: false
                pipeline: CppOverrideMainTrigger
                stage: TriggerStage
            CppOverridePR_Trigger:
                ignore_for_scheduling: false
                pipeline: CppOverridePR_Trigger
                stage: TriggerStage
        stages:
        -   CommonArtifactsStage:
                fetch_materials: false
                keep_artifacts: false
                clean_workspace: true
                approval:
                    type: success
                    allow_only_on_success: true
                jobs:
                    CommonArtifactsJob:
                        timeout: 0
                        resources:
                        -   Ubuntu-22
                        artifacts:
                        -   build:
                                source: CppOverride/*
                                destination: CppOverride
                        tasks:
                        -   script: |-
                                git clone https://github.com/Neko-Box-Coder/GoCD_CI_Scripts.git
                                mv ./GoCD_CI_Scripts/*.sh ./
                                mv ./GoCD_CI_Scripts/*.bat ./
                        -   fetch:
                                is_file: false
                                source: CppOverride
                                destination: CppOverridePR
                                pipeline: CppOverridePR_Trigger
                                stage: PopulateDetailsStage
                                job: PopulateDetailsJob
                                artifact_origin: gocd
                        -   fetch:
                                is_file: false
                                source: CppOverride
                                destination: CppOverrideMain
                                pipeline: CppOverrideMainTrigger
                                stage: PopulateDetailsStage
                                job: PopulateDetailsJob
                                artifact_origin: gocd
                                run_if: any
                        -   exec:
                                arguments:
                                -   -c
                                -   ./ChooseLatestFolder.sh ./CppOverridePR/CppOverride
                                    ./CppOverrideMain/CppOverride ./CppOverride
                                command: sh
                                run_if: any
                        -   exec:
                                arguments:
                                -   -lah
                                command: ls
                        -   exec:
                                arguments:
                                -   -lah
                                command: ls
                                working_directory: CppOverride
