site_name: Cpp Override
# theme: readthedocs
theme:
    # name: mkdocs
    # color_mode: dark
    # nav_style: primary
    # user_color_mode_toggle: true
    # navigation_depth: 3
    
    name: material
    custom_dir: overrides
    palette:
    -   scheme: slate
        primary: black
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
    -   scheme: default
        primary: black
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
    features:
    -   toc.follow
    -   toc.integrate
    -   navigation.sections
    -   content.code.copy
    -   content.code.select
    -   navigation.sections
    -   navigation.expand
    # -   navigation.tabs
    # -   navigation.tabs.sticky
    
    icon: 
        repo: fontawesome/brands/github

nav:
    -   index.md
    -   getting_started.md
    -   insert_overrides.md
    -   instruct_overrides.md
    -   inspect_overrides.md
    -   mock_class_generator.md
    -   override_external.md

repo_url: https://github.com/Neko-Box-Coder/CppOverride
repo_name: Neko-Box-Coder/CppOverride


extra_css: [extra.css]
markdown_extensions:
-   admonition
- pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.details
- pymdownx.superfences
-   toc:
      toc_depth: 2

extra:
    version:
        provider: mike
        default: latest
