site_name: Cpp Override
# theme: readthedocs
theme:
    # name: mkdocs
    # color_mode: dark
    # nav_style: primary
    # user_color_mode_toggle: true
    # navigation_depth: 3
    
    name: material
    palette:
    -   scheme: slate
        primary: black
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
    -   scheme: default
        primary: black
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
    features:
    -   toc.follow
    -   toc.integrate
    -   content.code.copy
    -   content.code.select


extra_css: [extra.css]
markdown_extensions:
-   admonition
- pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.details
- pymdownx.superfences
-   toc:
      toc_depth: 3
